<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Nova_X_Generator {

    private $themes_dir;

    public function __construct() {
        $this->themes_dir = get_theme_root();
    }

    public function build_theme( $site_title, $prompt ) {
        $site_title = sanitize_text_field( $site_title );
        $prompt     = sanitize_textarea_field( $prompt );

        // Safe theme slug
        $slug = sanitize_title( $site_title );
        if ( empty( $slug ) ) {
            $slug = 'nova-x-theme';
        }

        $target_dir = trailingslashit( $this->themes_dir ) . $slug;

        if ( file_exists( $target_dir ) ) {
            return [
                'success' => false,
                'message' => 'Theme folder already exists: ' . $slug,
            ];
        }

        wp_mkdir_p( $target_dir );

        // Minimal theme files
        $style_css = "/*
Theme Name: {$site_title}
Author: Nova-X
Version: 0.1.0
*/\n\nbody{font-family:system-ui,Arial,sans-serif;margin:0;padding:0;}\n";

        $functions_php = "<?php\nif(!defined('ABSPATH')){exit;}\nadd_theme_support('title-tag');\nadd_theme_support('post-thumbnails');\n";

        $index_php = "<?php get_header(); ?>\n<main style=\"padding:24px;\">\n  <h1><?php bloginfo('name'); ?></h1>\n  <p>Generated by Nova-X.</p>\n  <pre style=\"white-space:pre-wrap;background:#f7f7f7;padding:12px;border-radius:8px;\"><?php echo esc_html(" . var_export( $prompt, true ) . "); ?></pre>\n</main>\n<?php get_footer(); ?>\n";

        $header_php = "<!doctype html>\n<html <?php language_attributes(); ?>>\n<head>\n<meta charset=\"<?php bloginfo('charset'); ?>\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<?php wp_head(); ?>\n</head>\n<body <?php body_class(); ?>>\n<header style=\"padding:16px;border-bottom:1px solid #eee;\">\n  <strong><?php bloginfo('name'); ?></strong>\n</header>\n";

        $footer_php = "<footer style=\"padding:16px;border-top:1px solid #eee;\">\n  <small>Nova-X Theme Architect</small>\n</footer>\n<?php wp_footer(); ?>\n</body>\n</html>\n";

        $this->write_file( $target_dir . '/style.css', $style_css );
        $this->write_file( $target_dir . '/functions.php', $functions_php );
        $this->write_file( $target_dir . '/index.php', $index_php );
        $this->write_file( $target_dir . '/header.php', $header_php );
        $this->write_file( $target_dir . '/footer.php', $footer_php );

        return [
            'success' => true,
            'message' => 'Theme built successfully!',
            'path'    => $target_dir,
            'slug'    => $slug,
        ];
    }

    private function write_file( $path, $content ) {
        $handle = fopen( $path, 'w' );
        if ( $handle ) {
            fwrite( $handle, $content );
            fclose( $handle );
        }
    }
}
