<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class Nova_X_Generator {

    private $themes_dir;

    public function __construct() {
        $this->themes_dir = get_theme_root();
    }

    public function build_theme( $site_title, $prompt ) {
        $site_title = sanitize_text_field( $site_title );
        $prompt     = sanitize_textarea_field( $prompt );

        // Safe theme slug
        $slug = sanitize_title( $site_title );
        if ( empty( $slug ) ) {
            $slug = 'nova-x-theme';
        }

        // Append timestamp to ensure uniqueness (avoid doubling if already present)
        if ( ! preg_match( '/-\d{10}$/', $slug ) ) {
            $timestamp = time();
            $slug .= '-' . $timestamp;
        }

        $target_dir = trailingslashit( $this->themes_dir ) . $slug;

        // Check for duplicate directory before creation
        if ( file_exists( $target_dir ) ) {
            // Log the conflict
            error_log( '[Nova-X] Theme folder conflict detected - ' . $slug . ' at ' . $target_dir . ' — User ID: ' . get_current_user_id() );
            
            // Try to generate a new unique slug with microtime for additional uniqueness
            $microtime = (int) ( microtime( true ) * 1000 );
            $slug .= '-' . $microtime;
            $target_dir = trailingslashit( $this->themes_dir ) . $slug;
            
            // Final check - if still exists, return error
            if ( file_exists( $target_dir ) ) {
                error_log( '[Nova-X] Theme generation failed - Unable to create unique folder after retry for slug ' . $slug . ' — User ID: ' . get_current_user_id() );
                return [
                    'success' => false,
                    'message' => 'Unable to create unique theme folder. Please try again or contact support.',
                ];
            }
        }

        // Create directory
        $mkdir_result = wp_mkdir_p( $target_dir );
        
        if ( ! $mkdir_result ) {
            error_log( '[Nova-X] Failed to create theme directory: ' . $target_dir . ' — User ID: ' . get_current_user_id() );
            return [
                'success' => false,
                'message' => 'Failed to create theme directory. Please check file permissions.',
            ];
        }

        // Minimal theme files
        $style_css = "/*
Theme Name: {$site_title}
Author: Nova-X
Version: 0.1.0
*/\n\nbody{font-family:system-ui,Arial,sans-serif;margin:0;padding:0;}\n";

        $functions_php = "<?php\nif(!defined('ABSPATH')){exit;}\nadd_theme_support('title-tag');\nadd_theme_support('post-thumbnails');\n";

        $index_php = "<?php get_header(); ?>\n<main style=\"padding:24px;\">\n  <h1><?php bloginfo('name'); ?></h1>\n  <p>Generated by Nova-X.</p>\n  <pre style=\"white-space:pre-wrap;background:#f7f7f7;padding:12px;border-radius:8px;\"><?php echo esc_html(" . var_export( $prompt, true ) . "); ?></pre>\n</main>\n<?php get_footer(); ?>\n";

        $header_php = "<!doctype html>\n<html <?php language_attributes(); ?>>\n<head>\n<meta charset=\"<?php bloginfo('charset'); ?>\" />\n<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\n<?php wp_head(); ?>\n</head>\n<body <?php body_class(); ?>>\n<header style=\"padding:16px;border-bottom:1px solid #eee;\">\n  <strong><?php bloginfo('name'); ?></strong>\n</header>\n";

        $footer_php = "<footer style=\"padding:16px;border-top:1px solid #eee;\">\n  <small>Nova-X Theme Architect</small>\n</footer>\n<?php wp_footer(); ?>\n</body>\n</html>\n";

        // Write theme files and track failures
        $files_to_write = [
            'style.css' => $style_css,
            'functions.php' => $functions_php,
            'index.php' => $index_php,
            'header.php' => $header_php,
            'footer.php' => $footer_php,
        ];
        
        foreach ( $files_to_write as $filename => $content ) {
            $file_path = $target_dir . '/' . $filename;
            if ( ! $this->write_file( $file_path, $content ) ) {
                error_log( '[Nova-X] Theme generation failed - Could not write file: ' . $filename . ' for theme ' . $slug . ' — User ID: ' . get_current_user_id() );
                return [
                    'success' => false,
                    'message' => 'Failed to create theme file. Please check file permissions.',
                ];
            }
        }

        return [
            'success' => true,
            'message' => 'Theme built successfully!',
            'path'    => $target_dir,
            'slug'    => $slug,
        ];
    }

    private function write_file( $path, $content ) {
        $handle = fopen( $path, 'w' );
        if ( $handle ) {
            $written = fwrite( $handle, $content );
            fclose( $handle );
            
            if ( false === $written ) {
                error_log( '[Nova-X] File write failed - ' . basename( $path ) . ' in ' . dirname( $path ) . ' — User ID: ' . get_current_user_id() );
                return false;
            }
            return true;
        } else {
            error_log( '[Nova-X] Failed to open file for writing - ' . basename( $path ) . ' in ' . dirname( $path ) . ' — User ID: ' . get_current_user_id() );
            return false;
        }
    }
}
